name: alis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - numpy=1.21.2
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - dask=2021.10.0
  - matplotlib=3.5.1
  - pip=21.2.4
  - ipykernel=6.4.1
  - pip:
    - pytest=7.0.1